// !needs to be changed to not include personal data
const validMessages = [
    {
        'type':             20,
        'channel_id':       '1242465770299195462',
        'content':          'Success',
        'attachments':      [],
        'embeds':           [],
        'timestamp':        '2024-05-24T04:36:24.008000+00:00',
        'edited_timestamp': null,
        'flags':            0,
        'components':       [],
        'id':               '1243422325244825653',
        'author':           {
            'id':                     'test bot id',
            'username':               'Test',
            'avatar':                 null,
            'discriminator':          '6271',
            'public_flags':           0,
            'flags':                  0,
            'bot':                    true,
            'banner':                 null,
            'accent_color':           null,
            'global_name':            null,
            'avatar_decoration_data': null,
            'banner_color':           null,
            'clan':                   null
        },
        'mentions':         [],
        'mention_roles':    [],
        'pinned':           false,
        'mention_everyone': false,
        'tts':              false,
        'application_id':   '1242465242773192816',
        'interaction':      {
            'id':   '1243422323789402143',
            'type': 2,
            'name': 'remember-messages',
            'user': {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            }
        },
        'webhook_id':           '1242465242773192816',
        'position':             0,
        'interaction_metadata': {
            'id':      '1243422323789402143',
            'type':    2,
            'user_id': '330475170835726347',
            'user':    {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            },
            'authorizing_integration_owners': { '0': '1242218138586841188' },
            'name':                           'remember-messages'
        }
    },
    {
        'type':             20,
        'channel_id':       '1242465770299195462',
        'content':          'Success',
        'attachments':      [],
        'embeds':           [],
        'timestamp':        '2024-05-24T04:35:50.474000+00:00',
        'edited_timestamp': null,
        'flags':            0,
        'components':       [],
        'id':               '1243422184593162253',
        'author':           {
            'id':                     'test bot id',
            'username':               'Test',
            'avatar':                 null,
            'discriminator':          '6271',
            'public_flags':           0,
            'flags':                  0,
            'bot':                    true,
            'banner':                 null,
            'accent_color':           null,
            'global_name':            null,
            'avatar_decoration_data': null,
            'banner_color':           null,
            'clan':                   null
        },
        'mentions':         [],
        'mention_roles':    [],
        'pinned':           false,
        'mention_everyone': false,
        'tts':              false,
        'application_id':   '1242465242773192816',
        'interaction':      {
            'id':   '1243422182382505985',
            'type': 2,
            'name': 'remember-messages',
            'user': {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            }
        },
        'webhook_id':           '1242465242773192816',
        'position':             0,
        'interaction_metadata': {
            'id':      '1243422182382505985',
            'type':    2,
            'user_id': '330475170835726347',
            'user':    {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            },
            'authorizing_integration_owners': { '0': '1242218138586841188' },
            'name':                           'remember-messages'
        }
    },
    {
        'type':             20,
        'channel_id':       '1242465770299195462',
        'content':          'Success',
        'attachments':      [],
        'embeds':           [],
        'timestamp':        '2024-05-24T04:35:29.945000+00:00',
        'edited_timestamp': null,
        'flags':            0,
        'components':       [],
        'id':               '1243422098488168488',
        'author':           {
            'id':                     'test bot id',
            'username':               'Test',
            'avatar':                 null,
            'discriminator':          '6271',
            'public_flags':           0,
            'flags':                  0,
            'bot':                    true,
            'banner':                 null,
            'accent_color':           null,
            'global_name':            null,
            'avatar_decoration_data': null,
            'banner_color':           null,
            'clan':                   null
        },
        'mentions':         [],
        'mention_roles':    [],
        'pinned':           false,
        'mention_everyone': false,
        'tts':              false,
        'application_id':   '1242465242773192816',
        'interaction':      {
            'id':   '1243422096852516916',
            'type': 2,
            'name': 'remember-messages',
            'user': {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            }
        },
        'webhook_id':           '1242465242773192816',
        'position':             0,
        'interaction_metadata': {
            'id':      '1243422096852516916',
            'type':    2,
            'user_id': '330475170835726347',
            'user':    {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            },
            'authorizing_integration_owners': { '0': '1242218138586841188' },
            'name':                           'remember-messages'
        }
    },
    {
        'type':             20,
        'channel_id':       '1242465770299195462',
        'content':          'Success',
        'attachments':      [],
        'embeds':           [],
        'timestamp':        '2024-05-24T04:29:52.757000+00:00',
        'edited_timestamp': null,
        'flags':            0,
        'components':       [],
        'id':               '1243420684219318313',
        'author':           {
            'id':                     'test bot id',
            'username':               'Test',
            'avatar':                 null,
            'discriminator':          '6271',
            'public_flags':           0,
            'flags':                  0,
            'bot':                    true,
            'banner':                 null,
            'accent_color':           null,
            'global_name':            null,
            'avatar_decoration_data': null,
            'banner_color':           null,
            'clan':                   null
        },
        'mentions':         [],
        'mention_roles':    [],
        'pinned':           false,
        'mention_everyone': false,
        'tts':              false,
        'application_id':   '1242465242773192816',
        'interaction':      {
            'id':   '1243420682742923325',
            'type': 2,
            'name': 'remember-messages',
            'user': {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            }
        },
        'webhook_id':           '1242465242773192816',
        'position':             0,
        'interaction_metadata': {
            'id':      '1243420682742923325',
            'type':    2,
            'user_id': '330475170835726347',
            'user':    {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            },
            'authorizing_integration_owners': { '0': '1242218138586841188' },
            'name':                           'remember-messages'
        }
    },
    {
        'type':             20,
        'channel_id':       '1242465770299195462',
        'content':          'Success',
        'attachments':      [],
        'embeds':           [],
        'timestamp':        '2024-05-24T04:26:46.719000+00:00',
        'edited_timestamp': null,
        'flags':            0,
        'components':       [],
        'id':               '1243419903919132753',
        'author':           {
            'id':                     'test bot id',
            'username':               'Test',
            'avatar':                 null,
            'discriminator':          '6271',
            'public_flags':           0,
            'flags':                  0,
            'bot':                    true,
            'banner':                 null,
            'accent_color':           null,
            'global_name':            null,
            'avatar_decoration_data': null,
            'banner_color':           null,
            'clan':                   null
        },
        'mentions':         [],
        'mention_roles':    [],
        'pinned':           false,
        'mention_everyone': false,
        'tts':              false,
        'application_id':   '1242465242773192816',
        'interaction':      {
            'id':   '1243419901712928829',
            'type': 2,
            'name': 'remember-messages',
            'user': {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            }
        },
        'webhook_id':           '1242465242773192816',
        'position':             0,
        'interaction_metadata': {
            'id':      '1243419901712928829',
            'type':    2,
            'user_id': '330475170835726347',
            'user':    {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            },
            'authorizing_integration_owners': { '0': '1242218138586841188' },
            'name':                           'remember-messages'
        }
    },
    {
        'type':             20,
        'channel_id':       '1242465770299195462',
        'content':          'Success',
        'attachments':      [],
        'embeds':           [],
        'timestamp':        '2024-05-24T04:24:21.189000+00:00',
        'edited_timestamp': null,
        'flags':            0,
        'components':       [],
        'id':               '1243419293522333696',
        'author':           {
            'id':                     'test bot id',
            'username':               'Test',
            'avatar':                 null,
            'discriminator':          '6271',
            'public_flags':           0,
            'flags':                  0,
            'bot':                    true,
            'banner':                 null,
            'accent_color':           null,
            'global_name':            null,
            'avatar_decoration_data': null,
            'banner_color':           null,
            'clan':                   null
        },
        'mentions':         [],
        'mention_roles':    [],
        'pinned':           false,
        'mention_everyone': false,
        'tts':              false,
        'application_id':   '1242465242773192816',
        'interaction':      {
            'id':   '1243419289038356521',
            'type': 2,
            'name': 'remember-messages',
            'user': {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            }
        },
        'webhook_id':           '1242465242773192816',
        'position':             0,
        'interaction_metadata': {
            'id':      '1243419289038356521',
            'type':    2,
            'user_id': '330475170835726347',
            'user':    {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            },
            'authorizing_integration_owners': { '0': '1242218138586841188' },
            'name':                           'remember-messages'
        }
    },
    {
        'type':             20,
        'channel_id':       '1242465770299195462',
        'content':          'There was an error getting the messages',
        'attachments':      [],
        'embeds':           [],
        'timestamp':        '2024-05-24T04:22:47.244000+00:00',
        'edited_timestamp': null,
        'flags':            0,
        'components':       [],
        'id':               '1243418899488440355',
        'author':           {
            'id':                     'test bot id',
            'username':               'Test',
            'avatar':                 null,
            'discriminator':          '6271',
            'public_flags':           0,
            'flags':                  0,
            'bot':                    true,
            'banner':                 null,
            'accent_color':           null,
            'global_name':            null,
            'avatar_decoration_data': null,
            'banner_color':           null,
            'clan':                   null
        },
        'mentions':         [],
        'mention_roles':    [],
        'pinned':           false,
        'mention_everyone': false,
        'tts':              false,
        'application_id':   '1242465242773192816',
        'interaction':      {
            'id':   '1243418897466785813',
            'type': 2,
            'name': 'remember-messages',
            'user': {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            }
        },
        'webhook_id':           '1242465242773192816',
        'position':             0,
        'interaction_metadata': {
            'id':      '1243418897466785813',
            'type':    2,
            'user_id': '330475170835726347',
            'user':    {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            },
            'authorizing_integration_owners': { '0': '1242218138586841188' },
            'name':                           'remember-messages'
        }
    },
    {
        'type':             20,
        'channel_id':       '1242465770299195462',
        'content':          'There was an error getting the messages',
        'attachments':      [],
        'embeds':           [],
        'timestamp':        '2024-05-24T04:22:25.771000+00:00',
        'edited_timestamp': null,
        'flags':            0,
        'components':       [],
        'id':               '1243418809423892488',
        'author':           {
            'id':                     'test bot id',
            'username':               'Test',
            'avatar':                 null,
            'discriminator':          '6271',
            'public_flags':           0,
            'flags':                  0,
            'bot':                    true,
            'banner':                 null,
            'accent_color':           null,
            'global_name':            null,
            'avatar_decoration_data': null,
            'banner_color':           null,
            'clan':                   null
        },
        'mentions':         [],
        'mention_roles':    [],
        'pinned':           false,
        'mention_everyone': false,
        'tts':              false,
        'application_id':   '1242465242773192816',
        'interaction':      {
            'id':   '1243418807398301747',
            'type': 2,
            'name': 'remember-messages',
            'user': {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            }
        },
        'webhook_id':           '1242465242773192816',
        'position':             0,
        'interaction_metadata': {
            'id':      '1243418807398301747',
            'type':    2,
            'user_id': '330475170835726347',
            'user':    {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            },
            'authorizing_integration_owners': { '0': '1242218138586841188' },
            'name':                           'remember-messages'
        }
    },
    {
        'type':             20,
        'channel_id':       '1242465770299195462',
        'content':          'There was an error getting the messages',
        'attachments':      [],
        'embeds':           [],
        'timestamp':        '2024-05-24T04:21:27.556000+00:00',
        'edited_timestamp': null,
        'flags':            0,
        'components':       [],
        'id':               '1243418565252481139',
        'author':           {
            'id':                     'test bot id',
            'username':               'Test',
            'avatar':                 null,
            'discriminator':          '6271',
            'public_flags':           0,
            'flags':                  0,
            'bot':                    true,
            'banner':                 null,
            'accent_color':           null,
            'global_name':            null,
            'avatar_decoration_data': null,
            'banner_color':           null,
            'clan':                   null
        },
        'mentions':         [],
        'mention_roles':    [],
        'pinned':           false,
        'mention_everyone': false,
        'tts':              false,
        'application_id':   '1242465242773192816',
        'interaction':      {
            'id':   '1243418563730214953',
            'type': 2,
            'name': 'remember-messages',
            'user': {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            }
        },
        'webhook_id':           '1242465242773192816',
        'position':             0,
        'interaction_metadata': {
            'id':      '1243418563730214953',
            'type':    2,
            'user_id': '330475170835726347',
            'user':    {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            },
            'authorizing_integration_owners': { '0': '1242218138586841188' },
            'name':                           'remember-messages'
        }
    },
    {
        'type':             20,
        'channel_id':       '1242465770299195462',
        'content':          'There was an error getting the messages',
        'attachments':      [],
        'embeds':           [],
        'timestamp':        '2024-05-24T04:21:06.471000+00:00',
        'edited_timestamp': null,
        'flags':            0,
        'components':       [],
        'id':               '1243418476815712331',
        'author':           {
            'id':                     'test bot id',
            'username':               'Test',
            'avatar':                 null,
            'discriminator':          '6271',
            'public_flags':           0,
            'flags':                  0,
            'bot':                    true,
            'banner':                 null,
            'accent_color':           null,
            'global_name':            null,
            'avatar_decoration_data': null,
            'banner_color':           null,
            'clan':                   null
        },
        'mentions':         [],
        'mention_roles':    [],
        'pinned':           false,
        'mention_everyone': false,
        'tts':              false,
        'application_id':   '1242465242773192816',
        'interaction':      {
            'id':   '1243418474349592607',
            'type': 2,
            'name': 'remember-messages',
            'user': {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            }
        },
        'webhook_id':           '1242465242773192816',
        'position':             0,
        'interaction_metadata': {
            'id':      '1243418474349592607',
            'type':    2,
            'user_id': '330475170835726347',
            'user':    {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            },
            'authorizing_integration_owners': { '0': '1242218138586841188' },
            'name':                           'remember-messages'
        }
    },
    {
        'type':             20,
        'channel_id':       '1242465770299195462',
        'content':          'There was an error getting the messages',
        'attachments':      [],
        'embeds':           [],
        'timestamp':        '2024-05-24T04:12:02.975000+00:00',
        'edited_timestamp': null,
        'flags':            0,
        'components':       [],
        'id':               '1243416197228134504',
        'author':           {
            'id':                     'test bot id',
            'username':               'Test',
            'avatar':                 null,
            'discriminator':          '6271',
            'public_flags':           0,
            'flags':                  0,
            'bot':                    true,
            'banner':                 null,
            'accent_color':           null,
            'global_name':            null,
            'avatar_decoration_data': null,
            'banner_color':           null,
            'clan':                   null
        },
        'mentions':         [],
        'mention_roles':    [],
        'pinned':           false,
        'mention_everyone': false,
        'tts':              false,
        'application_id':   '1242465242773192816',
        'interaction':      {
            'id':   '1243416195047358525',
            'type': 2,
            'name': 'remember-messages',
            'user': {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            }
        },
        'webhook_id':           '1242465242773192816',
        'position':             0,
        'interaction_metadata': {
            'id':      '1243416195047358525',
            'type':    2,
            'user_id': '330475170835726347',
            'user':    {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            },
            'authorizing_integration_owners': { '0': '1242218138586841188' },
            'name':                           'remember-messages'
        }
    },
    {
        'type':             20,
        'channel_id':       '1242465770299195462',
        'content':          'There was an error getting the messages',
        'attachments':      [],
        'embeds':           [],
        'timestamp':        '2024-05-24T04:11:29.718000+00:00',
        'edited_timestamp': null,
        'flags':            0,
        'components':       [],
        'id':               '1243416057738428426',
        'author':           {
            'id':                     'test bot id',
            'username':               'Test',
            'avatar':                 null,
            'discriminator':          '6271',
            'public_flags':           0,
            'flags':                  0,
            'bot':                    true,
            'banner':                 null,
            'accent_color':           null,
            'global_name':            null,
            'avatar_decoration_data': null,
            'banner_color':           null,
            'clan':                   null
        },
        'mentions':         [],
        'mention_roles':    [],
        'pinned':           false,
        'mention_everyone': false,
        'tts':              false,
        'application_id':   '1242465242773192816',
        'interaction':      {
            'id':   '1243416055330902077',
            'type': 2,
            'name': 'remember-messages',
            'user': {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            }
        },
        'webhook_id':           '1242465242773192816',
        'position':             0,
        'interaction_metadata': {
            'id':      '1243416055330902077',
            'type':    2,
            'user_id': '330475170835726347',
            'user':    {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            },
            'authorizing_integration_owners': { '0': '1242218138586841188' },
            'name':                           'remember-messages'
        }
    },
    {
        'type':             20,
        'channel_id':       '1242465770299195462',
        'content':          'Success',
        'attachments':      [],
        'embeds':           [],
        'timestamp':        '2024-05-24T04:09:26.579000+00:00',
        'edited_timestamp': null,
        'flags':            0,
        'components':       [],
        'id':               '1243415541256032307',
        'author':           {
            'id':                     'test bot id',
            'username':               'Test',
            'avatar':                 null,
            'discriminator':          '6271',
            'public_flags':           0,
            'flags':                  0,
            'bot':                    true,
            'banner':                 null,
            'accent_color':           null,
            'global_name':            null,
            'avatar_decoration_data': null,
            'banner_color':           null,
            'clan':                   null
        },
        'mentions':         [],
        'mention_roles':    [],
        'pinned':           false,
        'mention_everyone': false,
        'tts':              false,
        'application_id':   '1242465242773192816',
        'interaction':      {
            'id':   '1243415538558959639',
            'type': 2,
            'name': 'remember-messages',
            'user': {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            }
        },
        'webhook_id':           '1242465242773192816',
        'position':             0,
        'interaction_metadata': {
            'id':      '1243415538558959639',
            'type':    2,
            'user_id': '330475170835726347',
            'user':    {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            },
            'authorizing_integration_owners': { '0': '1242218138586841188' },
            'name':                           'remember-messages'
        }
    },
    {
        'type':             20,
        'channel_id':       '1242465770299195462',
        'content':          'Success',
        'attachments':      [],
        'embeds':           [],
        'timestamp':        '2024-05-24T04:08:56.118000+00:00',
        'edited_timestamp': null,
        'flags':            0,
        'components':       [],
        'id':               '1243415413493207110',
        'author':           {
            'id':                     'test bot id',
            'username':               'Test',
            'avatar':                 null,
            'discriminator':          '6271',
            'public_flags':           0,
            'flags':                  0,
            'bot':                    true,
            'banner':                 null,
            'accent_color':           null,
            'global_name':            null,
            'avatar_decoration_data': null,
            'banner_color':           null,
            'clan':                   null
        },
        'mentions':         [],
        'mention_roles':    [],
        'pinned':           false,
        'mention_everyone': false,
        'tts':              false,
        'application_id':   '1242465242773192816',
        'interaction':      {
            'id':   '1243415408858370058',
            'type': 2,
            'name': 'remember-messages',
            'user': {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            }
        },
        'webhook_id':           '1242465242773192816',
        'position':             0,
        'interaction_metadata': {
            'id':      '1243415408858370058',
            'type':    2,
            'user_id': '330475170835726347',
            'user':    {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            },
            'authorizing_integration_owners': { '0': '1242218138586841188' },
            'name':                           'remember-messages'
        }
    },
    {
        'type':             20,
        'channel_id':       '1242465770299195462',
        'content':          'Success',
        'attachments':      [],
        'embeds':           [],
        'timestamp':        '2024-05-24T04:07:56.193000+00:00',
        'edited_timestamp': null,
        'flags':            0,
        'components':       [],
        'id':               '1243415162149408838',
        'author':           {
            'id':                     'test bot id',
            'username':               'Test',
            'avatar':                 null,
            'discriminator':          '6271',
            'public_flags':           0,
            'flags':                  0,
            'bot':                    true,
            'banner':                 null,
            'accent_color':           null,
            'global_name':            null,
            'avatar_decoration_data': null,
            'banner_color':           null,
            'clan':                   null
        },
        'mentions':         [],
        'mention_roles':    [],
        'pinned':           false,
        'mention_everyone': false,
        'tts':              false,
        'application_id':   '1242465242773192816',
        'interaction':      {
            'id':   '1243415156101480529',
            'type': 2,
            'name': 'remember-messages',
            'user': {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            }
        },
        'webhook_id':           '1242465242773192816',
        'position':             0,
        'interaction_metadata': {
            'id':      '1243415156101480529',
            'type':    2,
            'user_id': '330475170835726347',
            'user':    {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            },
            'authorizing_integration_owners': { '0': '1242218138586841188' },
            'name':                           'remember-messages'
        }
    },
    {
        'type':             20,
        'channel_id':       '1242465770299195462',
        'content':          'Success',
        'attachments':      [],
        'embeds':           [],
        'timestamp':        '2024-05-24T04:07:24.861000+00:00',
        'edited_timestamp': null,
        'flags':            0,
        'components':       [],
        'id':               '1243415030733602922',
        'author':           {
            'id':                     'test bot id',
            'username':               'Test',
            'avatar':                 null,
            'discriminator':          '6271',
            'public_flags':           0,
            'flags':                  0,
            'bot':                    true,
            'banner':                 null,
            'accent_color':           null,
            'global_name':            null,
            'avatar_decoration_data': null,
            'banner_color':           null,
            'clan':                   null
        },
        'mentions':         [],
        'mention_roles':    [],
        'pinned':           false,
        'mention_everyone': false,
        'tts':              false,
        'application_id':   '1242465242773192816',
        'interaction':      {
            'id':   '1243415027298471966',
            'type': 2,
            'name': 'remember-messages',
            'user': {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            }
        },
        'webhook_id':           '1242465242773192816',
        'position':             0,
        'interaction_metadata': {
            'id':      '1243415027298471966',
            'type':    2,
            'user_id': '330475170835726347',
            'user':    {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            },
            'authorizing_integration_owners': { '0': '1242218138586841188' },
            'name':                           'remember-messages'
        }
    },
    {
        'type':             20,
        'channel_id':       '1242465770299195462',
        'content':          'Success',
        'attachments':      [],
        'embeds':           [],
        'timestamp':        '2024-05-24T03:48:49.784000+00:00',
        'edited_timestamp': null,
        'flags':            0,
        'components':       [],
        'id':               '1243410353761685654',
        'author':           {
            'id':                     'test bot id',
            'username':               'Test',
            'avatar':                 null,
            'discriminator':          '6271',
            'public_flags':           0,
            'flags':                  0,
            'bot':                    true,
            'banner':                 null,
            'accent_color':           null,
            'global_name':            null,
            'avatar_decoration_data': null,
            'banner_color':           null,
            'clan':                   null
        },
        'mentions':         [],
        'mention_roles':    [],
        'pinned':           false,
        'mention_everyone': false,
        'tts':              false,
        'application_id':   '1242465242773192816',
        'interaction':      {
            'id':   '1243410352025374821',
            'type': 2,
            'name': 'remember-messages',
            'user': {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            }
        },
        'webhook_id':           '1242465242773192816',
        'position':             0,
        'interaction_metadata': {
            'id':      '1243410352025374821',
            'type':    2,
            'user_id': '330475170835726347',
            'user':    {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            },
            'authorizing_integration_owners': { '0': '1242218138586841188' },
            'name':                           'remember-messages'
        }
    },
    {
        'type':             20,
        'channel_id':       '1242465770299195462',
        'content':          'Success',
        'attachments':      [],
        'embeds':           [],
        'timestamp':        '2024-05-24T03:46:18.502000+00:00',
        'edited_timestamp': null,
        'flags':            0,
        'components':       [],
        'id':               '1243409719239114853',
        'author':           {
            'id':                     'test bot id',
            'username':               'Test',
            'avatar':                 null,
            'discriminator':          '6271',
            'public_flags':           0,
            'flags':                  0,
            'bot':                    true,
            'banner':                 null,
            'accent_color':           null,
            'global_name':            null,
            'avatar_decoration_data': null,
            'banner_color':           null,
            'clan':                   null
        },
        'mentions':         [],
        'mention_roles':    [],
        'pinned':           false,
        'mention_everyone': false,
        'tts':              false,
        'application_id':   '1242465242773192816',
        'interaction':      {
            'id':   '1243409717599014982',
            'type': 2,
            'name': 'remember-messages',
            'user': {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            }
        },
        'webhook_id':           '1242465242773192816',
        'position':             0,
        'interaction_metadata': {
            'id':      '1243409717599014982',
            'type':    2,
            'user_id': '330475170835726347',
            'user':    {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            },
            'authorizing_integration_owners': { '0': '1242218138586841188' },
            'name':                           'remember-messages'
        }
    },
    {
        'type':             20,
        'channel_id':       '1242465770299195462',
        'content':          'Success',
        'attachments':      [],
        'embeds':           [],
        'timestamp':        '2024-05-24T03:41:40.635000+00:00',
        'edited_timestamp': null,
        'flags':            0,
        'components':       [],
        'id':               '1243408553780187169',
        'author':           {
            'id':                     'test bot id',
            'username':               'Test',
            'avatar':                 null,
            'discriminator':          '6271',
            'public_flags':           0,
            'flags':                  0,
            'bot':                    true,
            'banner':                 null,
            'accent_color':           null,
            'global_name':            null,
            'avatar_decoration_data': null,
            'banner_color':           null,
            'clan':                   null
        },
        'mentions':         [],
        'mention_roles':    [],
        'pinned':           false,
        'mention_everyone': false,
        'tts':              false,
        'application_id':   '1242465242773192816',
        'interaction':      {
            'id':   '1243408552379285566',
            'type': 2,
            'name': 'remember-messages',
            'user': {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            }
        },
        'webhook_id':           '1242465242773192816',
        'position':             0,
        'interaction_metadata': {
            'id':      '1243408552379285566',
            'type':    2,
            'user_id': '330475170835726347',
            'user':    {
                'id':                     'real user id',
                'username':               'user_name',
                'avatar':                 'pic goes hard',
                'discriminator':          '0',
                'public_flags':           0,
                'flags':                  0,
                'banner':                 null,
                'accent_color':           null,
                'global_name':            'Test User',
                'avatar_decoration_data': null,
                'banner_color':           null,
                'clan':                   null
            },
            'authorizing_integration_owners': { '0': '1242218138586841188' },
            'name':                           'remember-messages'
        }
    }
];

module.exports = { validMessages };
