# This workflow will format your code on commit

name: formatter
run-name: ${{ github.actor }} is making your code pretty

on: [push, pull_request]

jobs:
  format-code:
    name: ESLint formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - name: Get changed files
        id: changed-files
        run: |
            if ${{ github.event_name == 'pull_request' }}; then
              echo "changed_files=$(git diff --name-only HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
            else if ${{ github.event_name == 'push' }}; then
              echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
            fi
      - run: npx eslint --fix ${{ steps.changed-files.outputs.changed_files }}